#!/usr/bin/env python3
"""
Assemble all 315 drafted entries into a single Typst source for a 6x9 PDF,
one devotional per page. Compile with: typst compile devotional.typ

Per draft format (from samples.md, locked):
  ## <Month Day>           — date header
  # <Saint Name>            — main name
  *italic epithet line*     — subtitle (life dates)
  body paragraphs (3-4)
  > *"pull-quote"* — attribution
"""

import json
import re
from pathlib import Path

ROOT = Path.home() / "acta-sanctorum/devotional"
DRAFTS = ROOT / "drafts"
OUT = ROOT / "devotional.typ"

MONTHS = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov"]


def md_inline_to_typst(text: str) -> str:
    """Convert a single line of markdown inline formatting to Typst."""
    # Escape backslashes and Typst special chars first (be conservative)
    text = text.replace("\\", "\\\\")
    text = text.replace("@", "\\@")
    text = text.replace("#", "\\#")
    text = text.replace("$", "\\$")
    # Markdown emphasis → Typst
    # **bold** → *bold*; *italic* → _italic_
    # Order matters: do bold first (double-star) then italic (single-star)
    text = re.sub(r"\*\*([^*]+?)\*\*", r"*\1*", text)
    text = re.sub(r"(?<!\*)\*([^*\n]+?)\*(?!\*)", r"_\1_", text)
    return text


def parse_entry(md_path: Path) -> dict:
    """Parse a draft .md into header/name/epithet/body/quote pieces."""
    text = md_path.read_text().strip()
    lines = text.split("\n")
    out = {"date": "", "name": "", "epithet": "", "body": [], "quote": ""}
    i = 0
    # ## Month Day
    while i < len(lines) and not lines[i].startswith("## "):
        i += 1
    if i < len(lines):
        out["date"] = lines[i][3:].strip()
        i += 1
    # # Saint Name
    while i < len(lines) and not lines[i].startswith("# "):
        i += 1
    if i < len(lines):
        out["name"] = lines[i][2:].strip()
        i += 1
    # blank line(s)
    while i < len(lines) and not lines[i].strip():
        i += 1
    # *epithet*
    if i < len(lines) and lines[i].startswith("*") and lines[i].rstrip().endswith("*"):
        out["epithet"] = lines[i].strip().strip("*").strip()
        i += 1
    # body paragraphs until blockquote
    while i < len(lines):
        if lines[i].startswith(">"):
            out["quote"] = lines[i].lstrip("> ").strip()
            break
        if lines[i].strip():
            out["body"].append(lines[i].strip())
        i += 1
    return out


def emit_entry(e: dict) -> str:
    """Render one entry as Typst, ending with a #pagebreak()."""
    parts = []
    # Invisible TOC marker: captures an abbreviated date + name; the Contents
    # page queries these and resolves each entry's page number via Typst.
    dp = e["date"].split()
    month = dp[0] if dp else e["date"]
    day = dp[1] if len(dp) >= 2 else ""
    parts.append(
        "#metadata((kind: \"toc\", month: "
        + json.dumps(month, ensure_ascii=False)
        + ", day: "
        + json.dumps(day, ensure_ascii=False)
        + ", name: "
        + json.dumps(e["name"], ensure_ascii=False)
        + "))"
    )
    parts.append("")
    # Date header (top of page, small caps, light)
    parts.append(f"#text(size: 9pt, fill: gray)[#smallcaps[{md_inline_to_typst(e['date'])}]]")
    parts.append("")
    parts.append("#v(0.6em)")
    # Saint name
    parts.append(f"#text(size: 20pt, weight: \"semibold\")[{md_inline_to_typst(e['name'])}]")
    parts.append("")
    # Epithet
    if e["epithet"]:
        parts.append(f"#text(size: 11pt, style: \"italic\", fill: rgb(\"#444\"))[{md_inline_to_typst(e['epithet'])}]")
        parts.append("")
    parts.append("#v(0.5em)")
    parts.append("")
    # Body paragraphs
    for para in e["body"]:
        parts.append(md_inline_to_typst(para))
        parts.append("")
    # Pull-quote
    if e["quote"]:
        q = md_inline_to_typst(e["quote"])
        parts.append("#v(0.4em)")
        parts.append(f"#block(inset: (left: 0.8em), stroke: (left: 0.5pt + gray))[#text(size: 9.5pt)[{q}]]")
    parts.append("")
    parts.append("#pagebreak(weak: true)")
    return "\n".join(parts)


HEADER = r"""// Acta Sanctorum Devotional — 6x9 trade paperback
// Generated by tools/build-pdf.py

#set text(
  font: ("EB Garamond 12", "Cormorant Garamond", "Baskerville", "Times New Roman"),
  size: 11pt,
  hyphenate: true,
)

#set par(
  leading: 0.38em,
  spacing: 0.45em,
  justify: true,
  first-line-indent: (amount: 1em, all: false),
)

#show heading: set text(font: ("EB Garamond 12", "Cormorant Garamond"))

// Footer: page number (outer corner) + ornament (center)
// Defined as a function so we can suppress on title page
#let _footer = context {
  let n = counter(page).at(here()).first()
  let num = counter(page).display()
  set text(size: 9pt, fill: rgb("#888"))
  grid(
    columns: (1fr, auto, 1fr),
    align(left)[#if calc.even(n) [#num]],
    align(center)[#text(size: 11pt)[❦]],
    align(right)[#if calc.odd(n) [#num]],
  )
}

#set page(
  width: 6in,
  height: 9in,
  margin: (top: 0.6in, bottom: 0.6in, inside: 0.7in, outside: 0.6in),
  footer: _footer,
  footer-descent: 0.1in,
)

// =========================================================================
// FRONT MATTER — roman numerals, no folios on the display pages
// =========================================================================
#counter(page).update(1)
#set page(numbering: "i")

// --- Half-title (recto) ---
#page(footer: none)[
  #align(center)[
    #v(2.3in)
    #text(size: 24pt, tracking: 5pt)[ACTA SANCTORVM]
  ]
]

// --- Frontispiece (verso) — the engraved title-page of the Acta ---
#page(footer: none)[
  #align(center + horizon)[
    #image("cover/engraving.png", width: 3.05in)
    #v(0.7em)
    #text(size: 8pt, style: "italic", fill: gray)[The engraved title-page of the]
    #linebreak()
    #text(size: 8pt, style: "italic", fill: gray)[_Acta Sanctorum_ (Paris: Victor Palmé, 1863)]
  ]
]

// --- Title page (recto) ---
#page(footer: none)[
  #align(center)[
    #v(1.3in)
    #text(size: 34pt, weight: "semibold")[Acta Sanctorum]
    #v(0.4em)
    #text(size: 18pt, style: "italic")[A Daily Devotional]
    #v(1.1em)
    #text(size: 13pt, fill: rgb("#7c6a4e"))[❦]
    #v(1.1em)
    #text(size: 11.5pt)[Three hundred fifteen lives of the saints,]
    #linebreak()
    #text(size: 11.5pt)[from the first of January to the tenth of November]
    #v(1fr)
    #text(size: 12.5pt, style: "italic")[Wilson Pruitt]
    #v(0.45in)
    #text(size: 10pt, tracking: 2pt, fill: rgb("#555"))[WROOT PRESS]
    #v(0.2in)
  ]
]

// --- Copyright (verso) ---
#page(footer: none)[
  #set text(size: 9.5pt)
  #set par(leading: 0.5em, spacing: 0.7em, first-line-indent: 0pt, justify: false)
  #v(1fr)
  #align(center)[
    _Acta Sanctorum: A Daily Devotional_

    Copyright © 2026 Wilson Pruitt

    All rights reserved. No part of this book may be reproduced in any form without written permission from the publisher, except for brief quotations in a review.

    Published by Wroot Press.

    The English renderings of the _Acta Sanctorum_ are the editor's own, made from the Latin of the Bollandist edition. The pull-quote that closes each entry is drawn, save where otherwise marked, from the Bollandist source.

    The cover and frontispiece reproduce the engraved title-page of the _Acta Sanctorum_ (Paris: Victor Palmé, 1863).

    Set in EB Garamond.

    First edition, 2026 · isbn 979-8-18408-405-3

    _actasanctorum.org_
  ]
  #v(0.5in)
]

// --- Epigraph (recto) ---
#page(footer: none)[
  #align(center + horizon)[
    #block(width: 72%)[
      #set par(leading: 0.6em, justify: false)
      #text(size: 12.5pt, style: "italic")[Therefore, seeing we also are compassed about with so great a cloud of witnesses, let us run with patience the race that is set before us.]
      #v(1.2em)
      #text(size: 10pt, tracking: 1.5pt, fill: gray)[HEBREWS 12:1]
    ]
  ]
]

#pagebreak(to: "odd")

// --- Contents (recto) ---
#heading(level: 1, outlined: false, numbering: none)[#text(size: 22pt, weight: "semibold")[Contents]]
#v(0.8em)
#context {
  // Front-matter entries (roman folios)
  let fronts = query(metadata).filter(it => type(it.value) == dictionary and it.value.at("kind", default: none) == "front")
  set text(size: 10pt)
  for it in fronts {
    let pg = counter(page).at(it.location()).first()
    block(below: 0.4em)[#it.value.title#box(width: 1fr, repeat[#text(fill: rgb("#cccccc"))[.]])#h(0.4em)#numbering("i", pg)]
  }
  v(0.7em)
  // Daily entries, grouped by month
  let items = query(metadata).filter(it => type(it.value) == dictionary and it.value.at("kind", default: none) == "toc")
  set text(size: 9pt)
  set par(justify: false, leading: 0.4em, first-line-indent: 0pt, hanging-indent: 1.6em)
  columns(2, gutter: 1.5em, {
    let lastmonth = ""
    for it in items {
      let pg = counter(page).at(it.location()).first()
      if it.value.month != lastmonth {
        lastmonth = it.value.month
        block(above: 0.85em, below: 0.4em, breakable: false)[#text(weight: "semibold", size: 9pt, fill: rgb("#7c6a4e"))[#smallcaps(it.value.month)]]
      }
      block(below: 0.3em)[#box(width: 1.5em)[#align(right)[#text(fill: rgb("#888"))[#it.value.day]]]#h(0.5em)#it.value.name#box(width: 1fr, repeat[#text(fill: rgb("#cccccc"))[.]])#h(0.4em)#pg]
    }
  })
  // Back-matter entries (arabic folios)
  let backs = query(metadata).filter(it => type(it.value) == dictionary and it.value.at("kind", default: none) == "back")
  if backs.len() > 0 {
    v(0.8em)
    set text(size: 10pt)
    for it in backs {
      let pg = counter(page).at(it.location()).first()
      block(below: 0.4em)[#it.value.title#box(width: 1fr, repeat[#text(fill: rgb("#cccccc"))[.]])#h(0.4em)#pg]
    }
  }
}

#pagebreak(to: "odd")

// --- Preface (recto) ---
#metadata((kind: "front", title: "Preface"))
#heading(level: 1, outlined: false, numbering: none)[#text(size: 22pt, weight: "semibold")[Preface]]

#v(1em)

This book is a daily companion drawn from the great compendium of Christian hagiography, the _Acta Sanctorum_, gathered and edited from 1607 forward by the Bollandist Society of Antwerp. The Bollandists set themselves the task of collecting, sifting, and printing every credible _vita_ of every saint of the Christian East and West, day by day through the calendar year. The work continued for three hundred years; sixty-eight folio volumes appeared between 1643 and 1940, reaching as far through the calendar as the early days of November before publication effectively halted.

Three hundred and fifteen entries follow here, one for each day from the first of January to the tenth of November — the calendar reach of the published _Acta_. Each entry is grounded in the _Acta_'s own treatment of the day's saint: where the Bollandists wrote, the entry draws from what they wrote; where they declined to write, the entry yields the day to a saint they did treat substantively. Twelve great Christological and Marian feasts of the modern Roman calendar — the Presentation, the Annunciation, the Visitation, the Transfiguration, the Assumption, the Nativity of Mary, the Holy Cross, the Guardian Angels, the Rosary, All Saints, All Souls, the Dedication of the Lateran — are not represented as feasts here, because the Bollandists did not write substantive lives for them. Each yields, on its day, to a particular saint whose life the _Acta_ preserve. The Roman calendar holds the feasts; this book holds the saints.

The voice across the entries is meant for slow reading. Each is about three hundred and forty words, the length of a short morning's attention, in three or four paragraphs that move from a scene through the substance of the life into a quiet turn at the end. The aim is the _Lives of the Saints_ tradition that runs from Butler in the eighteenth century to Daniel-Rops in the twentieth — narrative, literary, and unhurried, neither apologetic nor hagiographic. A pull-quote closes each entry. Most quotes are from the Bollandist source itself. The few exceptions are quietly marked.

The fuller machinery of this project — the Bollandist source files in Latin, the audit of every pick, the record of the correction passes that brought the calendar into its present shape — lives at _actasanctorum.org_. Readers who want to follow a saint back to the _Acta_ will find a path there. The book in your hand is the surface of a much longer work.

#pagebreak()

// =========================================================================
// BODY — arabic numerals starting at 1
// =========================================================================
#counter(page).update(1)
#set page(numbering: "1")

"""


AFTERWORD = r"""
#pagebreak()
#metadata((kind: "back", title: "Afterword"))
#heading(level: 1, outlined: false, numbering: none)[#text(size: 22pt, weight: "semibold")[Afterword]]

#v(1em)

This book ends where the _Acta Sanctorum_ ends. The Bollandists worked through the calendar in order, a volume at a time, and they were still working when the world overtook them. The last of their great folios to treat the saints day by day reach only into the early part of November; the volume for the tenth, where this book closes, was among the final ones to appear. December was never finished in the same fashion. In 1940, as a second war broke over Europe, the society issued a single supplementary volume for December — a martyrology rather than a gathering of lives — and the three-hundred-year labor of the day-by-day _Acta_ came, in effect, to rest a few weeks short of the year's end.

It was not for want of will. The original Society of Bollandists — named for Jean Bolland, who took up at Antwerp the plan Heribert Rosweyde had drawn in 1607 — was suppressed in 1788, in the upheavals that scattered the old Catholic learning, its library broken up and its presses stopped. Half a century later, in 1837, the Bollandists were revived at Brussels, and they have worked without interruption since. But they did not take the folios up again and drive them to December. The age of the great calendar had passed; what the work now required was tools — to sort the genuine from the spurious, to catalogue every manuscript life of every saint. And so the modern Bollandists turned to that: to the journal _Analecta Bollandiana_, begun in 1882 and still appearing; to the _Bibliotheca Hagiographica_ that indexes the lives in Latin, Greek, and the languages of the East; to the patient critical method of scholars like Hippolyte Delehaye, who taught the Church to read its own legends with reverence and honesty at once. They are at the work still, in Brussels.

So the tenth of November is not an arbitrary stopping place. It is the edge of an unfinished thing — the point where one of the longest labors in the history of Christian scholarship set down its pen, and where its heirs took up a different one. This book has followed the saints only as far as the Bollandists carried them. Beyond it lie the rest of November, and December, and all the saints the calendar still keeps.
"""


def main():
    entries = []
    for mo in MONTHS:
        mo_dir = DRAFTS / mo
        if not mo_dir.exists():
            continue
        for f in sorted(mo_dir.glob("day-*.md")):
            entries.append(parse_entry(f))

    print(f"parsed {len(entries)} entries")

    body = "\n".join(emit_entry(e) for e in entries)
    OUT.write_text(HEADER + body + AFTERWORD)
    print(f"wrote {OUT}")
    print("now run: typst compile", OUT)


if __name__ == "__main__":
    main()
